### PR TITLE
Energizing

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### Reference Issues/PRs
#99 
#### What does this implement/fix? Explain your changes.
- Energizing program added

#### Any other comments?
References:

1. https://www.yogabasics.com/practice/pranayama/

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@sadrasabouri Could you please update `PROGRAMS.md`? Once that's done, I will finalize this pull request.

**Comment by sadrasabouri** [comment]
> @sadrasabouri Could you please update `PROGRAMS.md`? Once that's done, I will finalize this pull request.

Sure, It's done now.

**Comment by sepandhaghighi** [comment]
> > @sadrasabouri Could you please update `PROGRAMS.md`? Once that's done, I will finalize this pull request.
> 
> Sure, It's done now.

@sadrasabouri Thanks 💯 
Kindly review this PR; if all is well, please **squash/merge** it after approval.

**Review by sadrasabouri — APPROVED** [review]
LG

**Pull request merged**
